import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

class GFG2 {

    public static byte[] getSHA(String input)
            throws NoSuchAlgorithmException {

        // Create SHA-256 object
        MessageDigest md =
                MessageDigest.getInstance("SHA-256");

        // Generate hash
        return md.digest(
                input.getBytes(StandardCharsets.UTF_8));
    }

    public static String toHexString(byte[] hash) {

        // Convert byte array into signum representation
        BigInteger number =
                new BigInteger(1, hash);

        // Convert digest into hex value
        StringBuilder hexString =
                new StringBuilder(number.toString(16));

        // Add leading zeros
        while (hexString.length() < 64) {
            hexString.insert(0, '0');
        }

        return hexString.toString();
    }

    public static void main(String args[]) {

        try {

            System.out.println(
                    "HashCode Generated by SHA-256 for:");

            String s2 = "hello world";

            System.out.println("\n" + s2 + " : "
                    + toHexString(getSHA(s2)));

            String s3 = "K1t4fo0V";

            System.out.println("\n" + s3 + " : "
                    + toHexString(getSHA(s3)));

        }

        catch (NoSuchAlgorithmException e) {

            System.out.println(
                    "Exception thrown: " + e);
        }
    }
}